# Generated by Django 4.1.7 on 2023-08-21 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.JSONField(blank=True, null=True)),
                ('education_score', models.DecimalField(decimal_places=13, max_digits=16)),
                ('education_color', models.CharField(default='#00E5BC', max_length=30)),
                ('language_score', models.DecimalField(decimal_places=13, max_digits=16)),
                ('language_color', models.CharField(default='#FF0038', max_length=30)),
                ('special_skills_score', models.DecimalField(decimal_places=13, max_digits=16)),
                ('special_skills_color', models.CharField(default='#00A8E1', max_length=30)),
                ('sport_score', models.DecimalField(decimal_places=13, max_digits=16)),
                ('sport_color', models.CharField(default='#09959A', max_length=30)),
                ('work_experiance_score', models.DecimalField(decimal_places=13, max_digits=16)),
                ('work_experiance_color', models.CharField(default='#FFCB05', max_length=30)),
                ('program_score', models.DecimalField(decimal_places=13, max_digits=16)),
                ('program_color', models.CharField(default='#8800E0', max_length=30)),
                ('report_file', models.FileField(upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
