# Generated by Django 4.1.7 on 2023-08-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_reportmodel_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportmodel',
            options={'verbose_name': 'ReportModel'},
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
