# Generated by Django 4.1.7 on 2023-08-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usercv_certificatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueRandom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_value', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
