# Generated by Django 4.1.7 on 2023-08-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_filecategory_allows_multiple_files'),
        ('users', '0007_alter_certificatemodel_cert_unique_key'),
    ]

    operations = [
    ]
