# Generated by Django 4.1.7 on 2023-08-28 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userverificationfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatemodel',
            name='cert_file',
        ),
        migrations.RemoveField(
            model_name='certificatemodel',
            name='cert_unique_key',
        ),
        migrations.RemoveField(
            model_name='certificatemodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reportmodel',
            name='report_file',
        ),
        migrations.RemoveField(
            model_name='reportmodel',
            name='user',
        ),
        migrations.CreateModel(
            name='UserAccountFilePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_category', models.CharField(choices=[('CV', 'V'), ('REPORT', 'REPORT'), ('CERTIFICATE', 'CERTIFICATE')], max_length=20)),
                ('file_key', models.UUIDField(editable=False, unique=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to=users.models.user_account_file_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.useraccountfilepage'),
        ),
    ]
