# Generated by Django 4.1.7 on 2023-08-28 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_certificatemodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccountfilepage',
            old_name='report_file',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='certificate_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_file', to='users.useraccountfilepage'),
        ),
        migrations.AlterField(
            model_name='reportmodel',
            name='report_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_file', to='users.useraccountfilepage'),
        ),
    ]
