# Generated by Django 4.1.7 on 2023-08-28 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_report_file_useraccountfilepage_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquerandom',
            options={'verbose_name': 'UniqueRandom', 'verbose_name_plural': 'UniqueRandoms'},
        ),
        migrations.AlterModelOptions(
            name='userverificationfile',
            options={'verbose_name': 'UserVerificationFile', 'verbose_name_plural': 'UserVerificationFiles'},
        ),
        migrations.AddField(
            model_name='uniquerandom',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
