# Generated by Django 4.1.7 on 2023-08-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_useraccountfilepage_date_crated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatemodel',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
