# Generated by Django 4.1.7 on 2023-08-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_weight_store',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
