# Generated by Django 4.1.7 on 2023-07-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_question_question_dependens_on_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='stage_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
