# Generated by Django 4.1.7 on 2023-07-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_question_stage_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='questionIdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.question'),
        ),
    ]
