# Generated by Django 4.1.7 on 2023-07-19 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_answer_questionidd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='stage_index',
            new_name='question_index',
        ),
    ]
