# Generated by Django 4.1.7 on 2023-08-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_stage_index_question_question_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['stage__stage_name', 'question_index'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='age',
        ),
    ]
