# Generated by Django 4.1.7 on 2023-08-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_useraccount_username_useraccount_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
