# Generated by Django 4.1.7 on 2023-08-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_weight',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
