# Generated by Django 4.1.7 on 2023-08-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_answer_answer_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_weight_for_hashing',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
